Cherry-pick important .gitlab-ci.yml changes from develop

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,4 @@
-image: nx/ci:1.20
+image: nx/ci
 
 include:
   - project: "dev/ci"
@@ -9,11 +9,12 @@ include:
 
 default:
   tags:
-    - service
+    - us-service
 
 variables:
-  JENKINS_JOB_LOG: "true"
   JUNKSHOP_ENABLED: "false"
+  # These variables are required for deploy cloud
+  K8S_PRODUCT_RELEASE: cp-mr-${CI_MERGE_REQUEST_IID}
 
 workflow:
   rules:
@@ -30,43 +31,33 @@ stages:
   - docker image
   - check
   - build
+  - deploy
   - test
   - fail-fast
 
-.retries:
-  interruptible: true
-  retry:
-    max: 2
-    when:
-      - runner_system_failure
-      - stuck_or_timeout_failure
-      - scheduler_failure
-#
-.frontend-changes:
-  extends: .retries
-  needs:
-    - job: docker:build-node-chrome
-      optional: true
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
-      changes:
-        - front_end/**/*
+# Rules
 
-.get_target_branch_script:
-  script:
-  - set -e
-  - if [[ "$CI_COMMIT_REF_PROTECTED" == "true" ]]; then
-  -   TARGET_BRANCH_NAME=${CI_COMMIT_REF_NAME}
-  - else
-  -   TARGET_BRANCH_NAME=$(get_target_protected_branch.py
-        --gitlab-server-url=${CI_SERVER_URL}
-        --gitlab-token="${GITLAB_API_TOKEN}"
-        --project-id=${CI_PROJECT_ID}
-        --merge-request-iid=${CI_MERGE_REQUEST_IID})
-  - fi
+.enable_for_mr: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+
+.frontend_changes:
+  - front_end/**/*
+  - .gitlab-ci.yml
+
+.notification_changes:
+ - desktop_notifications/**/*
+ - .gitlab-ci.yml
+
+.webadmin_changes:
+  - front_end/**/*
+  - webadmin/**/*
+
+.enable_for_mr_branch: '( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^vms_/ ||
+  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" )'
+
+.enable_for_protected_branch: '( $CI_PIPELINE_SOURCE == "push" &&
+  ( $CI_COMMIT_REF_NAME =~ /^vms_/ || $CI_COMMIT_REF_NAME == "develop" ) )'
 
 no-changes:
-#  extends: .retries
   needs: []
   rules:
       - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
@@ -81,7 +72,6 @@ no-changes:
     - echo "If this is the only job that runs then no changes were made that requires the pipeline"
 
 .backend-changes:
-  extends: .retries
   needs:
     - job: docker:build-django-python
       optional: true
@@ -170,16 +160,17 @@ django-unit-test-fast:
     - pytest -m "not integration" -m "not slow" --create-db --junitxml=fast-report.xml --cov="." --cov-report xml:fast-coverage.xml --cov-report term
 
 .frontend-node:
-  extends: .frontend-changes
   variables:
     CHROME_BIN: /usr/bin/google-chrome
     FRONTEND_NODE_MODULES: /node_modules_frontend
     ES_LINT_PLUGIN_NODE_MODULES: /node_modules_es_lint_plugin
-
   image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
   before_script:
     - cp -r "$FRONTEND_NODE_MODULES" ./front_end/node_modules
     - cp -r "$ES_LINT_PLUGIN_NODE_MODULES" ./front_end/eslint-plugin-nx/node_modules
+  rules:
+  - if: !reference [ .enable_for_mr ]
+    changes: [ .frontend_changes ]
 
 other-frontend-checks:
   extends: .frontend-node
@@ -249,58 +240,171 @@ frontend-tests:
       #   popd
       # popd
 
-jenkings-builds:
-  extends: .frontend-changes
+.jenkins-builds:
   stage: build
   image: nx/ci
-  tags:
-  - ru-moscow
-  artifacts:
-    paths:
-      - logs/**/*
   secrets:
     JENKINS_API_TOKEN_FILE: !reference [.tokens, secrets, JENKINS_API_TOKEN_FILE]
+
+jenkins-build-webadmin:
+  extends: .jenkins-builds
   script:
-    - mkdir logs
-    - SOME_BUILD_FAILED=false
-    - echo "Running webadmin and frontend builds in parallel"
+    - |
+      set -ex
+      if [[ "$CI_COMMIT_REF_PROTECTED" == true ]]; then
+        PUBLISH=ON
+      else
+        PUBLISH=OFF
+      fi
+    - echo "Running webadmin build"
     - runJenkinsJob.sh gitlab.vms.review.webadmin.build
+      "PUBLISH=$PUBLISH"
       "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
       "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
-      "GITLAB_COMMIT=$CI_COMMIT_SHORT_SHA"
-      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
-      "GITLAB_JOB_ID=$CI_JOB_ID"
-      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
-      "GITLAB_JOB_URL=$CI_JOB_URL" 1> logs/webadmin.log 2>&1  & WEBADMIN_EXIT="$?"
-    - runJenkinsJob.sh gitlab.cloud.frontend
-      "PUSH_TO_ARTIFACTORY=true"
-      "BRANCH=$TARGET_BRANCH_NAME"
-      "BUILD_IDENTITY=$CI_PIPELINE_ID"
-      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
-      "GITLAB_COMMIT=$CI_COMMIT_SHORT_SHA"
+      "GITLAB_COMMIT=$CI_COMMIT_SHA"
       "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
       "GITLAB_JOB_ID=$CI_JOB_ID"
       "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
       "GITLAB_JOB_URL=$CI_JOB_URL"
-      "REVISION=$CI_COMMIT_SHORT_SHA" 1> logs/frontend.log 2>&1 & FRONTEND_EXIT="$?"
-    - wait
-    - if [ "$WEBADMIN_EXIT" != "0" ]; then SOME_BUILD_FAILED=true && echo "Webadmin build failed $WEBADMIN_EXIT"; else echo "Webadmin build successful"; fi
-    - if [ "$FRONTEND_EXIT" != "0" ]; then SOME_BUILD_FAILED=true && echo "Frontend build failed $FRONTEND_EXIT"; else echo "Frontend build successful"; fi
-    - if $SOME_BUILD_FAILED; then exit 1; fi
-
-wheel-uploader:
-  extends: .retries
-  stage: pre-build
-  script:
-    - mkdir ~/.nxcloud
-    - >
-      echo "auth: $NXCLOUD_UTIL_SERVICE_AUTH" > ~/.nxcloud/config.yaml
-    - curl -L hdw.mx/linux/nxcloud | tee ./nxcloud > /dev/null && chmod +x ./nxcloud
-    - cat cloud/requirements.txt | ./nxcloud runCommand UploadWheels
+      "GITLAB_REFSPEC=$CI_COMMIT_SHA"
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
-      changes:
-        - cloud/requirements.txt
+  - if: !reference [ .enable_for_mr_branch ]
+    changes: !reference [ .webadmin_changes ]
+  - if: !reference [.enable_for_protected_branch]
+    changes: !reference [ .webadmin_changes ]
+
+#jenkins-build-frontend:
+#  extends: .jenkins-builds
+#  script:
+#    - echo "Running frontend build"
+#    - runJenkinsJob.sh gitlab.cloud.frontend
+#      "BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+#      "BUILD_IDENTITY=$CI_PIPELINE_ID"
+#      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
+#      "GITLAB_COMMIT=$CI_COMMIT_SHA"
+#      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
+#      "GITLAB_JOB_ID=$CI_JOB_ID"
+#      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
+#      "GITLAB_JOB_URL=$CI_JOB_URL"
+#      "REVISION=$CI_COMMIT_SHA"
+#  rules:
+#  - if: !reference [ .enable_for_mr_branch ]
+#    changes: !reference [ .frontend_changes ]
+#
+#jenkins-build-notification:
+#  extends: .jenkins-builds
+#  script:
+#    - echo "Running notification build"
+#    - runJenkinsJob.sh gitlab.cloud.notification
+#      "BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+#      "BUILD_IDENTITY=$CI_PIPELINE_ID"
+#      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
+#      "GITLAB_COMMIT=$CI_COMMIT_SHA"
+#      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
+#      "GITLAB_JOB_ID=$CI_JOB_ID"
+#      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
+#      "GITLAB_JOB_URL=$CI_JOB_URL"
+#      "REVISION=$CI_COMMIT_SHA"
+#  rules:
+#  - if: !reference [ .enable_for_mr_branch ]
+#    changes: !reference [ .notification_changes ]
+
+#cloud-deploy:
+#  extends: .jenkins-builds
+#  stage: deploy
+#  variables:
+#    CLOUD_BACKEND_IMAGE_TAG: latest
+#  script:
+#    - set -ex
+#    - runJenkinsJob.sh gitlab.cloud.deploy
+#        "CLOUD_PORTAL_IMAGE_TAG=${CI_PIPELINE_ID}.gitlab"
+#        "CLOUD_BACKEND_IMAGE_TAG=${CLOUD_BACKEND_IMAGE_TAG}"
+#        "RELEASE_NAME=${K8S_PRODUCT_RELEASE}"
+#        "CUSTOMIZATIONS=default" 2>&1 | tee "deploy.log"
+#    - |
+#      JENKINS_JOB_URL="$(grep 'Job Url:' "deploy.log" | \
+#        head -1 | \
+#        sed 's/\x1b\[[0-9;]*m//g' | \
+#        awk -F ': ' '{print $2}')"
+#    - curl
+#        --fail
+#        --silent
+#        --show-error
+#        -X GET
+#        --user "jenkins:$(cat "${JENKINS_API_TOKEN_FILE}")"
+#        "${JENKINS_JOB_URL}artifact/CLOUD_HOST.envvar" > cloud_host.env
+#  artifacts:
+#    reports:
+#      dotenv: cloud_host.env
+#  environment:
+#    name: ${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}
+#    url: https://${CLOUD_HOST}
+#    on_stop: cloud-remove-deployment
+#  rules:
+#  - if: !reference [ .enable_for_mr_branch ]
+#    changes: !reference [ .frontend_changes ]
+
+# stop deployment and clean all data, manual UI action. may be used to verify clean deployment
+# may be invoked using manual UI action to verify clean deployment
+# also triggered when MR branch deleted (MR merged)
+# ref: https://docs.gitlab.com/ee/ci/environments/#stop-an-environment-when-a-branch-is-deleted
+#cloud-remove-deployment:
+#  extends: .jenkins-builds
+#  stage: deploy
+#  variables:
+#    GIT_STRATEGY: none
+#  secrets:
+#    GITLAB_API_TOKEN: !reference [.tokens, secrets, GITLAB_API_TOKEN]
+#  script:
+#  - |
+#    GL_ENV_ID="$(curl --silent --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
+#      "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/environments?name=${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}" |
+#      jq ".[0].id")"
+#    CLOUD_URL="$(curl --silent --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
+#      "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/environments/${GL_ENV_ID}" |
+#      jq -r ".external_url")"
+#  - runJenkinsJob.sh gitlab.cloud.remove-deployment
+#    "CLOUD_HOST=${CLOUD_URL}"
+#  environment:
+#    name: ${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}
+#    action: stop
+#  rules:
+#  - if: !reference [ .enable_for_mr_branch ]
+#    changes: !reference [ .frontend_changes ]
+#    when: manual
+#    # ref: https://docs.gitlab.com/ee/ci/yaml/#rulesallow_failure
+#    # the directive also impacts pipeline stage representation on top level
+#    # without it, the stage status shown unclear (as a cog) even if deploy successful
+#    allow_failure: true
+
+create-vms-mr:
+  stage: deploy
+  extends: .jenkins-builds
+  needs: [ "jenkins-build-webadmin" ]
+  script:
+    - runJenkinsJob.sh gitlab.vms.review.webadmin.create-vms-mr
+      "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
+      "CLOUD_PORTAL_COMMIT=$CI_COMMIT_SHA"
+      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
+      "GITLAB_JOB_ID=$CI_JOB_ID"
+      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
+      "GITLAB_JOB_URL=$CI_JOB_URL"
+  rules:
+  - if: !reference [ .enable_for_protected_branch ]
+    changes: !reference [ .webadmin_changes ]
+
+#wheel-uploader:
+#  stage: pre-build
+#  script:
+#    - mkdir ~/.nxcloud
+#    - >
+#      echo "auth: $NXCLOUD_UTIL_SERVICE_AUTH" > ~/.nxcloud/config.yaml
+#    - curl -L hdw.mx/linux/nxcloud | tee ./nxcloud > /dev/null && chmod +x ./nxcloud
+#    - cat cloud/requirements.txt | ./nxcloud runCommand UploadWheels
+#  rules:
+#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+#      changes:
+#        - cloud/requirements.txt
 
 
 .fail-on:
@@ -348,9 +452,9 @@ on-frontend-tests:
   extends: .fail-on-frontend
   needs: ["frontend-tests"]
 
-on-jenkings-builds:
+on-jenkins-builds:
   extends: .fail-on-frontend
-  needs: ["jenkings-builds"]
+  needs: ["jenkins-build-webadmin"] # , "jenkins-build-frontend"]
 
 on-django-checks:
   extends: .fail-on-backend
@@ -364,14 +468,14 @@ on-django-tests-fast:
   extends: .fail-on-backend
   needs: ["django-unit-test-fast"]
 
-on-wheel-upload:
-  extends: .fail-on
-  needs: ["wheel-uploader"]
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
-      changes:
-        - cloud/requirements.txt
-      when: on_failure
+#on-wheel-upload:
+#  extends: .fail-on
+#  needs: ["wheel-uploader"]
+#  rules:
+#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+#      changes:
+#        - cloud/requirements.txt
+#      when: on_failure
 
 .hooker:
   image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
